name: 'Netlify Preview Deploy'

on:
  pull_request:
    types: ['opened', 'edited', 'synchronize']

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.qKnl5-oT3LvWqjJbbruh8nSU5nDnThu6bLV0ArxUKq4 }}
          NETLIFY_SITE_ID: ${{ secrets.deft-starship-bffdf1 }}
